package goaway

// DefaultFalsePositives is a list of words that may wrongly trigger the DefaultProfanities
var DefaultFalsePositives = []string{
	"arsenal",
	"assassin",
	"assaying", // was saying
	"assert",
	"assign",
	"assimil",
	"associat",
	"assum", // assuming, assumption, assumed
	"assur", // assurance
	"banal",
	"basement",
	"bass",
	"cass", // cassie, cassandra, carcass
	"butthe",
	"canvass",
	"circum",
	"clitheroe",
	"cockburn",
	"cocktail",
	"cumber",
	"cumbing",
	"cumulat",
	"dickvandyke",
	"document",
	"evaluate",
	"exclusive",
	"expensive",
	"explain",
	"expression",
	"grape",
	"grass",
	"harass",
	"hass",
	"horniman",
	"hotwater",
	"identit",
	"lass", // class
	"leafage",
	"libshitz",
	"magnacumlaude",
	"mass",
	"mocha",
	"pass", // compass, passion
	"penistone",
	"phoebe",
	"phoenix",
	"pushit",
	"sassy",
	"saturday",
	"serfage",
	"sexist", // systems exist, sexist
	"shoe",
	"scunthorpe",
	"shitake",
	"stitch",
	"sussex",
	"therapist",
	"tysongay",
	"wass",
	"wharfage",
}
